# Generated by Django 4.2.7 on 2023-11-27 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('unit', models.CharField(choices=[('кг', 'кг'), ('шт', 'шт'), ('мт', 'мт')], max_length=5, verbose_name='Единицы измерения')),
                ('remainder', models.FloatField(default=0, verbose_name='Остаток')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
                'ordering': ['-time_create'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_stock', models.CharField(max_length=200, unique=True, verbose_name='Название склада')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Пользователи')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
                'ordering': ['-time_create', 'name_stock'],
            },
        ),
        migrations.CreateModel(
            name='StockMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0, verbose_name='Количество')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.materials', verbose_name='Материал')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.stock', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Материал на складе',
                'verbose_name_plural': 'Материалы на складах',
            },
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('on_credit', models.BooleanField(default=False, verbose_name='Долг')),
                ('debtor_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя должника')),
                ('expenses_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата расхода')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.materials', verbose_name='Материал')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.stock', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Расход',
                'verbose_name_plural': 'Расходы',
                'ordering': ['-time_create'],
            },
        ),
        migrations.CreateModel(
            name='Coming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Оприходовано')),
                ('arrival_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата прихода')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.materials', verbose_name='Материал')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.stock', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Приход',
                'verbose_name_plural': 'Приходы',
                'ordering': ['-time_create'],
            },
        ),
    ]
