# Generated by Django 4.2.7 on 2023-11-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmaterials',
            name='avg_price',
            field=models.FloatField(default=0, editable=False, verbose_name='Средняя цена'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='remainder',
            field=models.FloatField(default=0, editable=False, verbose_name='Остаток'),
        ),
        migrations.AlterField(
            model_name='stockmaterials',
            name='quantity',
            field=models.FloatField(default=0, editable=False, verbose_name='Количество'),
        ),
    ]
